# fly.toml v2 app configuration file
app = "hexstrike-ai"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile.minimal"

[env]
  HEXSTRIKE_PORT = "8888"
  HEXSTRIKE_HOST = "0.0.0.0"

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

